name: Test Pynextsim

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    #container:
    #  image: nansencenter/pynextsim_testing:latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: nansencenter/nextsim-tools
          token: ${{ secrets.ACCESS_TOKEN }}
          path: nextsim-tools
      - uses: actions/checkout@v2
        with:
          repository: nansencenter/nextsimf
          token: ${{ secrets.ACCESS_TOKEN }}
          path: nextsimf
      - name: List current dir
        run: |
          ls -al 
          ls -al nextsim-tools
          ls -al nextsimf
          pwd
