name: Test Pynextsim

on:
  push:

jobs:
  test:
    env:
      PYTHONPATH: "/home/runner/work/test_nextsimf_actions/test_nextsimf_actions/nextsim-tools/python:/home/runner/work/test_nextsimf_actions/test_nextsimf_actions/nextsimf"
    runs-on: ubuntu-latest
    container:
      image: nansencenter/pynextsim_testing:latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: nansencenter/nextsim-tools
          token: ${{ secrets.ACCESS_TOKEN }}
          path: nextsim-tools
      - uses: actions/checkout@v2
        with:
          repository: nansencenter/nextsimf
          token: ${{ secrets.ACCESS_TOKEN }}
          path: nextsimf
      - name: List current dir
        run: |
          ls -al 
          ls -al nextsim-tools
          ls -al nextsimf
          pwd
          python -m pytest nextsim-tools/python/pynextsim/tests
          python -m pytest nextsimf/pynextsimf/tests
